### ISSUE TITLE
Fixed editor topbar

### ISSUE THREAD

**Issue by vonloxx** [Automattic/isolated-block-editor#217]
Hi! First of all, great work on this project!
I'm trying to add some functionality such as fixed editor top and I was able to achieve that with a custom component.
![fixed-editor-topbar-1](https://user-images.githubusercontent.com/1254357/227938748-21a005bf-ced4-4b75-865e-483c0add79cc.gif)

The issue is scrolling with, for example, the block inserter sidebar opened:
![fixed-editor-topbar-2](https://user-images.githubusercontent.com/1254357/227939501-baa40010-dd2d-4869-bbc4-1cf77894d72f.gif)
The right behavior should be to be "attached" to the topbar.

I've checked Gutenberg's components (block inserter and popover) and it seems it adds some scroll listeners to a parent container to follow the scroll but since I'm scrolling the whole document node, it won't work.

I could add the behaviors to the inserter sidebar and popover on my custom component but I wonder if anyone got ideas to properly handle/workaround this? Without too much "hacking"... ;)

**Comment by johngodley** [comment]
Have you tried using CSS `display:sticky`? We are doing the same thing and it works well. I don't think scroll listeners are involved.

**Comment by vonloxx** [comment]
I tweaked a bit the `.interface-interface-skeleton__editor` container (overrode the `overflow: hidden`) and was able to use `position: sticky` on the `.interface-interface-skeleton__header` container. But I still have to figure out how to deal with popover slot (it's children position are set in "runtime").
@johngodley Is there any example you could point out? 🙏

**Comment by vonloxx** [comment]
Ok, I think I got it. I've set `.interface-interface-skeleton` container to `position: relative` and then set `.popover-slot` container to `position:fixed`.
Here's the css/scss overrides:
```css
.iso-editor {
  .interface-interface-skeleton {
    position: relative !important;

    .interface-interface-skeleton__editor {
      overflow: inherit !important;
    
      .interface-interface-skeleton__header {
        position: sticky;
        top: 79px; /* change to var. */
      }
    }
  }

  .popover-slot {
    position: fixed;
    z-index: 30;
  }
}
```
